language: java
sudo: false
jdk:
  - oraclejdk8
deploy:
  provider: heroku
  api-key:
    secure: "$HEROKU_API_KEY"
  app: estimador
script:
  - mvn test
  - mvn cobertura:cobertura
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
