# APPLICATION
spring:
  application:
    name: Estimador
    description: Projeto desenvolvido para gerenciamento de estimativas.
    version: @project.version@
  profiles:
    active: dev

# SERVER
server:
  contextPath: /
  port: 9090
